### ISSUE TITLE
logout gomb

### ISSUE THREAD

**Issue by magwas** [edemo/Joomla_oauth_plugin#21]
Az ADA login mellett legyen kijelentkezés gomb, ami kijelentkeztet a joomla-ból, és
feljön egy ablak (fix div), amiben megkérdezi, hogy ki akar-e jelentkezni az ada-ból (igen/nem)

1. Megoldja a joomla-ból kilépést
2. Az ADA /v1/logout interface-én kilép az adából ajax-al 

**Részletesebben:**
dologout,, doadalogout   taskok,   logoutform template,  nyelvi szövegkonstansok a hu-HU.com_adalogin.ini és en_GB.com_adalogin.ini -be, adalogin.js, adalogin.xml modositása.

**dologout** public method a site/controller.php ban. joomla logout majd viewer display layout: logoutform

**doadalogout** public method a site/controller.php -ban. ajax hivás,result feldolgozás: üzenet kiirás.(site/assets/adalogin.js segitségével)

uj file **site/views/adalogin/tmpl/logoutform.php**
echo képernyő html  szöveg és gomb( JText-et használni)
button class: btn btnAdalogout

nyelvi ini fájlok kiegészitése **site/language/......com_adalogin.ini** fájlok

új file **site/assets/adalogin.js**

**adalogin.xml**  file jaavitása

**Comment by utopszkij** [comment]
joomla logout: $app = JFactory::getApplication();  $app->logout();

**Comment by utopszkij** [comment]
joomla multilanguage system: a tényleges szövegek a language/......com_adalogin.ini fájlokban vannak, egy-egy tokenhez rendelve. kiirásuk JText::_('token') formában. Javasolt COM_ADALOGIN_XXXX alaku tokenek használata

**Comment by utopszkij** [comment]
Az elovalasztok sw. átstrukturálása (joomla kiegészitőkké tétele során) a jobb oldali gombok a joomla filozofiájának megfelelően egy un. "modulba" fognak kerülni, tehát ezek kialakitása nem ennek a pluginnak a feladata lesz. A tervezett joomla kiegészitő struktura:
**com_adalogin** (ez a kiegészitő amin most dolgozunk)
**com_szavazo** (a jelölt adatok kezelést, szavazó ürlap megjelenitését, szavazásokat, szavazat törlést, eredmény kiértékelést és kijelzést végző kiegészités) 
**mod_szavazo_gombok** ( a jobb oldali gombok megjelenitését végző kiegészités)
Ezenkivül a web oldal használ még néhány könyvtári joomla kiegészitőt is (Jcomment, acabebackup, .....)

**Comment by Gerviba** [comment]
Pusholtam a logout-button branchbe.
+ Kiegészítettem a testJoomlaFramework.php-t, hogy működjön a logout unittestje.

Az e2e pedig olyan részen vérzik el, amit nem értek, mert elvileg a localhost:8080/components/com_adalogin/index.php-re kellene átirányítania, de ehelyett az alapértelmezett portra redirecteli. Ez a UIProcedures.py:15 előtt van valahol. Ha belenyúlok a tesztbe és manuálisan átírom még időben az url-t, akkor betölt és beírja, hogy "Teszt Elek". (Ebben az esetben: OK az e2e)

Ha minden okés a kóddal, akkor csinálok egy pull requestet.

**Comment by utopszkij** [comment]
Gerviba! Kösz a munkádat. De van egy gond úgy látom a site/assets/adalogin.js s file nincs betöltve!
Valahova  kellene ezt megoldani, valahogy igy (php):
...
$document = JFactory::getDocument();
$document->addScript(jsfile_full_path);
...

Javaslom a controller.php -ba a dologout methodba betenni.

**Comment by utopszkij** [comment]
További gond az, hogy a javascript kis/nagy betü érzékeny és a button onclick -ben nem ugyanugy van írva a rutin név mint ahogy a adalogin.js -ben.

**Comment by utopszkij** [comment]
A jelzett hibákat provizorikusan javitva kitettem a http://valasztoimozgalom.hu -ra.
Kijelentkezési kisérletre, a "kijelentkezek az ADA -ból" gombra kattintva a következő hibaüzenet jön ki:

Kijelentkezés sikeres
Szeretne kijelentkezni az ADA fiókjából is?

Hiba a kapcsolatban. Próbálkozzon újra.
Igen Kezdőlap

**Comment by Gerviba** [comment]
A hiba ezért történt: "XMLHttpRequest cannot load https://adatom.hu/ada/v1/logout. The 'Access-Control-Allow-Origin' header has a value 'https://adatom.hu' that is not equal to the supplied origin. Origin 'http://valasztoimozgalom.hu' is therefore not allowed access."
Ezt az ajax lekérésnél dobja vissza.

Ha CORS-al küldöm (withCredentials=true), akkor pedig: "XMLHttpRequest cannot load https://adatom.hu/ada/v1/logout. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://valasztoimozgalom.hu' is therefore not allowed access."

Szóval, ha akarjuk ezt, akkor szerintem egy 
<?php
    header("Access-Control-Allow-Origin: *");
    header("Access-Control-Allow-Credentials: true");
?>
szerver oldali kód megoldaná a problémát.

**Comment by Gerviba** [comment]
PDOauth -> #879
