### ISSUE TITLE
Az elovalasztok sw. átstrukturálása (joomla kiegészitőkké tétele)

### ISSUE THREAD

**Issue by utopszkij** [edemo/Joomla_oauth_plugin#23]
A tervezett joomla kiegészitő struktura:
**com_adalogin** (ez már megvan, de fejlesztendő)
**com_szavazo** (a jelölt adatok kezelést, szavazó ürlap megjelenitését, szavazásokat, szavazat törlést, eredmény kiértékelést és kijelzést végző kiegészités - új kiegészitő a jelenlegi kodot felhasználva )
**mod_szavazo_gombok** ( a jobb oldali gombok megjelenitését végző kiegészités - új kiegészitő a meglévő kodot felhasználva)

Ezenkivül a web oldal használ még néhány könyvtári joomla kiegészitőt is (Jcomment, acabebackup, .....)

**Comment by utopszkij** [comment]
Tulajdonképpen az a feladat nem is ide való, hanem egy új elovalasztok2018  repoba! Hasonlóan a teszt szerver létrehozásához is.

**Comment by magwas** [comment]
Ide mehet: https://huboard.com/edemo/elovalasztok2018/
