### ISSUE TITLE
login with ada popup felh.felt. adatkezelés a kis popupban jelenik meg.

### ISSUE THREAD

**Issue by magwas** [edemo/Joomla_oauth_plugin#26]
egy iframe-ben jelenítse meg az ada login oldalt

**Comment by utopszkij** [comment]
Én kb egy éve kértem, hogy ezt oldjuk meg....

**Comment by utopszkij** [comment]
nagy papámnak a hétvégén velem kell jácania. Nem ér ra ezzel foglalkozni 
Német Merse 11 éves

**Comment by utopszkij** [comment]
:)

**Comment by utopszkij** [comment]
Megcsináltam, firefoxon teszteltem (még minden máson tesztelni kell!). Több gond van vele:
- a login form és a regiszt form eltérő méretü ezt nem tudom iframe -el esztétikusan kezelni, a javasript popup -ot pedig sok böngésző letiltja vagy új "fülre" konvertálja.
- ha regisztrálásnál a user a "felhasználási feltételek" linkre kattint akkor tragédia van :(

**Comment by utopszkij** [comment]
Teszteltem. chrome, firefox, IE  elfogadható mindegyiken (kivéve a "felhasználói feltételek" linket).

**Comment by utopszkij** [comment]
![image](https://cloud.githubusercontent.com/assets/5842680/21778501/e55f8474-d6a3-11e6-8923-f98b20abb9f1.png)

valasztoimozgalom.hu -> AD login -> Regisztrálás -> Felhasználói feltételek

**Comment by utopszkij** [comment]
én félek hogy egyes reklám blokkolok letiltanák

**Comment by krosza** [comment]
Majd kiirjuk vhova, hogy kapcsold ki, vagy  rekd be az ada t a kivetelek
koze

**Comment by Gerviba** [comment]
Én úgy tudom, hogy onclick-ből nem tiltja le.
Ezt teszteltem az Opera beépített adblockjával és Firefoxon adblockplus-al:

`window.open("https://....", "_blank", "width=500,height=600,top="+((window.innerHeight/2)-300)+",left="+((window.innerWidth/2)-250)+",menubar=no,status=no,toolbar=no,titlebar=n");`

A functiont amiben benne volt, egy button onclick eseményből hívtam meg.

**Comment by utopszkij** [comment]
jo, megcsinálom.

**Comment by utopszkij** [comment]
Megcsináltam, teszteltem IE, ff, chrome aktuális verziókban.
Kérlek teszteljétek minnél több böngészőn, eszközön és reklám blokkolóval!
https://valasztoimozgalom.hu

**Comment by Gerviba** [comment]
Szerintem UX szempontból jobb lenne a középre nyitott.

Debian GNU/Linux 8 x64:
- Opera 41.0.2353.69 [OK]
- Firefox 45.5.0 [OK]

iOS:
- Google Chrome [OK, új lapon nyitja meg]
- Safari [OK, új lapon nyitja meg]

**Comment by utopszkij** [comment]
android 42 chrome  uj lapon nyitja meg, gyári browser popup de rssz a mrete.

**Comment by utopszkij** [comment]
Mai tesztem szerint a popup ablakban a "Regisztraokl" gomb click utáni "felhasználó feltételek" és "adatkezelési tájékoztató" még mindig a kis popup -ban jelenik meg - ami nem jó.

Megoldási javaslat:

<script type="text/javascript>
.....
window.opener.location = "...........";
......
</script>

**Comment by utopszkij** [comment]
valasztoimozgalo.hu -n tesztelhető. A felhasználói feltételek, adatkezelés még nem jó (a kis popup ablakban jelenik meg)

**Comment by magwas** [comment]
ez a jegy wontfix. Gyuri átdúrja a login.html-t olyanra, mint a facebook, és utána rendezzük itt a dolgokat.
