### ISSUE TITLE
Login popup felület standard popup ablakba iframe helyett

### ISSUE THREAD

**Issue by Gerviba** [edemo/Joomla_oauth_plugin#27]
Ütközés a #26-os issueval.

**Comment by utopszkij** [comment]
Átirtam, kérlek teszteljétek minnél több böngészővel és reklám blokkolóval!

**Comment by utopszkij** [comment]
Gerviba!   Szeretnélek egy szívességre megkérni - ha időd engedi - akkor a https://github.com/utopszkij/pvoks repo -hoz segitenél unittest rendszert beüzemelni? Erről nekem fogalmam sincs, és úgy látom te pedig profi vagy ebben a témában, annak is örülnék ha megpróbálnád nekem elmagyarázni a dolog müködését.

privát email cimem: tibor.fogler@gmail.com skype: foglert, facebook: https://www.facebook.com/utopszkij.almodozo
