### ISSUE TITLE
test folyamat elszáll

### ISSUE THREAD

**Issue by utopszkij** [edemo/Joomla_oauth_plugin#28]
/root/87f138e1-e7d5-4655-b0da-fca35fe1752b.sh: tools/script: /bin/bash^M: bad interpreter: No such file or directory

lásd developer branch

**Comment by magwas** [comment]
Valahogyan sikerült windows line endinget tenni a file-ba, és azt nem szereti a linux. Mindjárt jön a fix.

**Comment by magwas** [comment]
Érdemes várni a merge-el addig, amíg zöld nem lesz.

**Comment by magwas** [comment]
most már valami más baja van szerintem...

**Comment by utopszkij** [comment]
Sajnos én most is pont ugyanazt a hibaüzenetet látom. :( Ezen kivül nem értem mi okozta a bajt, mindent pontosan úgy csináltam, mint eddig.... ?

**Comment by magwas** [comment]
#30 
A szövegszerkesztődben elmentetted a tools/script scriptet. A hülye pedig lecserélte a sorvégeket windózosra.

**Comment by utopszkij** [comment]
e2e test error:
 branch: feature/login_window (develop -ba, master -be nem mertem beküldeni)

======================================================================
ERROR: test_login (LoginTest.LoginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/src/github.com/edemo/Joomla_oauth_plugin/end2endtest/LoginTest.py", line 18, in test_login
    self.loginWithSSO()
  File "/root/src/github.com/edemo/Joomla_oauth_plugin/end2endtest/UIProcedures.py", line 11, in loginWithSSO
    self.fillInField("LoginForm_email_input", "mag+blog@magwas.rulez.org")
  File "/root/src/github.com/edemo/Joomla_oauth_plugin/end2endtest/UIActions.py", line 41, in fillInField
    element = self.waitUntilElementEnabled(fieldId)
  File "/root/src/github.com/edemo/Joomla_oauth_plugin/end2endtest/UIActions.py", line 31, in waitUntilElementEnabled
    element = WebDriverWait(self.driver, 100).until(element_to_be_useable((By.ID,fieldId)))
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by magwas** [comment]
@Claymanus  ez az a rész, ahol az ada teszt szerverhez megy tokenért. Nézd már meg légy szíves, hogy az sso törte-e? Itt a mozi: http://adadocs.demokracia.rulez.org/joomla_oauth_plugin/136/record.flv

**Comment by magwas** [comment]
2:14-nél van a szexjelenet.

**Comment by Claymanus** [comment]
ki tudod szedni belőle az url-t valahogy?

**Comment by utopszkij** [comment]
A login_window branch most zöld, a develop viszont piros, rebuild után is. A két branch compare viszont azt mondja nincs köztük különbség......akkor most mi van?
